
spring.application.name=order-service
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/orderdb?options=-c%20TimeZone=Asia/Kolkata
spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata
spring.jackson.time-zone=Asia/Kolkata
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis


# Product Service
resilience4j.circuitbreaker.instances.productService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.productService.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.productService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.productService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.productService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.productService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.productService.permittedNumberOfCallsInHalfOpenState=3


# User Service
resilience4j.circuitbreaker.instances.userService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.userService.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.userService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.userService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.userService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.userService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.userService.permittedNumberOfCallsInHalfOpenState=3


management.endpoints.web.exposure.include=health,info,metrics,circuitbreakers,circuitbreakerevents

management.endpoint.health.show-details=always

management.health.circuitbreakers.enabled=true


resilience4j.retry.instances.userService.maxAttempts=3
resilience4j.retry.instances.userService.waitDuration=2s
resilience4j.retry.instances.userService.enableExponentialBackoff=true
resilience4j.retry.instances.userService.exponentialBackoffMultiplier=2

resilience4j.retry.instances.productService.maxAttempts=3
resilience4j.retry.instances.productService.waitDuration=2s
resilience4j.retry.instances.productService.enableExponentialBackoff=true
resilience4j.retry.instances.productService.exponentialBackoffMultiplier=2